# Generated by Django 5.0.1 on 2024-04-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileira', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'livre'), (1, 'ocupado')])),
            ],
        ),
    ]
